### PR TITLE
1092 fix cacheing

### LINKED ISSUE #1070: Cannot upload new project if another one is loaded
I've uploaded a project from file called `*ex2.json` and it loaded correctly.
Then I decided to load another project, called `*ex1.json` but once I've clicked `Open` icon, then I couldn't load another file.
The area to drag and drop was locked on the previous file.

https://github.com/yaptide/ui/assets/7374733/932128df-49b1-4ae2-840a-368073eab3aa

### LINKED ISSUE #1092: Broken cacheing (memoization) for plots display
I've tried to run several simulations using the UI.
It seems that the results are not properly loaded onto the plots now.

I've started from example 1, limited the scoring only to Z-profile. Then I've submitted the simulation.
Then I've adjusted the detector to have only 5 bins along Z axis. I've correct reply from the backend with 5 numbers:
image

The problem is that the JSROOT plot wasn't updated with newly calculated and displayed the results of previous simulation.

The export to CSV worked properly:
image

To avoid issues with caching this was tested on a new private window.

### PR DESCRIPTION
**Pull request by Derstilon**
closes #1092

### CODE REVIEW

File: buildPython.js [hunk 1]
```diff
@@ -70,7 +70,9 @@ const saveFileName = (destFolder, fileName) => {
 		});
 
 		const activateCmd =
-			os.platform() === 'win32' ? 'venv\\Scripts\\activate.ps1' : '. venv/bin/activate';
+			os.platform() === 'win32'
```
Comment (grzanka) [inline buildPython.js:73]: You can borrow some code from 
https://github.com/yaptide/ui/pull/1087/files#diff-8fde42b3d73fc28682a0aa0f818786554c7ae677ae6721de3ef8618bbfd42ef4

but still I am not sure if it works

Comment (grzanka) [reply buildPython.js:73]: Can we withdraw that change, it can be possibly merge if https://github.com/yaptide/ui/pull/1087 is accepted by @ostatni5

**Comment by grzanka** [comment]
Fix conflicts here

File: src/JsRoot/GraphData.tsx [hunk 2]
```diff
@@ -177,7 +181,7 @@ export function generateGraphs(estimator: EstimatorResults, groupQuantities?: bo
 		.map(({ page, graph, filter }, idx) => {
 			return (
 				<Grid
-					key={`graph_${name}_${idx}`}
+					key={`graph_${name}${jobId ? '_' + jobId : ''}_${idx}`}
```
Comment (grzanka) [inline src/JsRoot/GraphData.tsx:184]: was that the crucial fix ?

**Comment by grzanka** [comment]
Simulations are not visible on the list:

image

**Comment by grzanka** [comment]
UI permanently asks for status of completed jobs, see many calls to `/direct/` API:

image

**Review by grzanka — CHANGES_REQUESTED** [review]
doesn't work

File: src/util/Notation/Notation.ts [hunk 3]
```diff
@@ -0,0 +1,109 @@
+import {
```
Comment (grzanka) [inline src/util/Notation/Notation.ts:1]: Is this our own code or borrowed from some Internet resources ?

**Comment by grzanka** [comment]
@Derstilon can you fix failing tests as well ?

File: src/util/Notation/Notation.ts (hunk 3 above)
Comment (Derstilon) [reply src/util/Notation/Notation.ts:1]: my code moved from type transform file to utils, because only types should be there.

**Review by grzanka — APPROVED** [review]

File: src/services/ShSimulatorService.tsx [hunk 4]
```diff
@@ -303,13 +303,35 @@ const ShSimulation = ({ children }: ShSimulationProps) => {
...
+							task.simulatedPrimaries = task.requestedPrimaries; //TODO: fix backend response and remove this line
+						}
+						return true;
+					}
+				}
+				return false;
+			});
+		}
+		return true;
+	};
```
Comment (ostatni5) [inline src/services/ShSimulatorService.tsx:326]: Make less

File: src/types/TypeTransformUtil.tsx [hunk 5]
```diff
@@ -1,17 +1,70 @@
...
+			: never
+		: ValidForSnakeize<R, false, Full>
+	: Full;
+
+// Determine if a string is valid for camelize
+// Should not contain whitespace, or dashes
+// Should not start with an underscore
+// Should contain at least one underscore
+// Should not contain mixed case
+// return T or never
```
Comment (ostatni5) [inline src/types/TypeTransformUtil.tsx:27]: Make better

**Review by ostatni5 — CHANGES_REQUESTED** [review]
obraz

File: src/JsRoot/GraphData.tsx (hunk 2 above)
Comment (Derstilon) [reply src/JsRoot/GraphData.tsx:184]: Partially yes

File: src/ThreeEditor/components/Dialog/SaveFileDialog.tsx [hunk 6]
```diff
@@ -1,35 +1,37 @@
...
-export type SaveFileProps = {
-	open: boolean;
-	onClose: () => void;
-	onConfirm: (data: {}, fileName: string) => void;
-	editor: YaptideEditor;
+const saveJson = (data: {}, fileName: string) => {
+	let output = undefined;
+	try {
+		output = JSON.stringify(data, null, '\t');
+		output = output.replace(/[\n\t]+([\d.e\-[\]]+)/g, '$1');
```
[the remark this answers is not in the document]
Comment (Derstilon) [reply src/ThreeEditor/components/Dialog/SaveFileDialog.tsx:13]: The regular expression is defined as /[\n\t]+([\d.e\-[\]]+)/g. The first part of the regular expression, [\n\t]+, matches one or more occurrences of either a newline or a tab character. The second part of the regular expression, ([\d.e\-[\]]+), matches one or more occurrences of a numeric value, including scientific notation and negative values. The parentheses around this part of the regular expression capture the matched value so that it can be used in the replacement string.

The regular expression is used with the replace method to replace any occurrence of one or more newlines or tabs followed by a numeric value with just the numeric value. The replacement string is $1, which refers to the captured numeric value from the regular expression.

**Review by ostatni5 — DISMISSED** [review]
obraz

**Review by grzanka — DISMISSED** [review]

**Comment by grzanka** [comment]
@ostatni5 @Derstilon there are some discussions left. I leave "Approve". If you are satisfied with the code then "Resolve" the discussions. Otherwise fix the things pointed in the review and merge yourselves once you are happy.

**Review by ostatni5 — CHANGES_REQUESTED** [review]
Move "adding lines to new pr"

**Review by ostatni5 — APPROVED** [review]
