### PR TITLE
Fix simulator exclusion between project and simulation window Issue: #1601

### LINKED ISSUE #1601: Running SHIELD-HIT12A - only example should be possible only with SHIELD-HIT12A simulator
Each project in yaptide has a proper simulator type.
For shieldhit project when user tries to run such project the UI should not ask user whether to run it with Fluka or SHIELD-HIT12A. Only SHIELD-HIT12A should be allowed.

https://github.com/yaptide/ui/assets/7374733/f90b22af-26bc-4eb1-9cb8-7c374314b5dd

### PR DESCRIPTION
**Pull request by lkwinta**
Fixes #1601 

This pull request includes several changes aimed at enhancing the simulation components by introducing a new `SimulatorType` and `SimulatorNames` mapping, and updating various components to utilize these new types.

Key changes include:

### Enhancements to Simulation Components:

* `src/WrapperApp/components/Simulation/BackendSimulations/BackendSimulations.tsx`:
  - Added `SimulatorType` import and included `simulator` in `BackendSimulationsProps` and component props. [[1]](diffhunk://#diff-b3bd6222cf0d4820a1038c2d52bae812bbc23a5f82984ef02498bb5172a2d35dR6) [[2]](diffhunk://#diff-b3bd6222cf0d4820a1038c2d52bae812bbc23a5f82984ef02498bb5172a2d35dR24) [[3]](diffhunk://#diff-b3bd6222cf0d4820a1038c2d52bae812bbc23a5f82984ef02498bb5172a2d35dR120)

* `src/WrapperApp/components/Simulation/RunSimulationForm.tsx`:
  - Added `SimulatorNames` import and created `simulatorMenuItems` for dynamic simulator selection. [[1]](diffhunk://#diff-6b97099161ab32ba4fdb9ffce871d09afde260be58e0ee0b12b74c65ae392f89L23-R23) [[2]](diffhunk://#diff-6b97099161ab32ba4fdb9ffce871d09afde260be58e0ee0b12b74c65ae392f89R160-R174)
  - Updated form controls to use `defaultSimulator` and `simulatorMenuItems` for simulator selection. [[1]](diffhunk://#diff-6b97099161ab32ba4fdb9ffce871d09afde260be58e0ee0b12b74c65ae392f89R252) [[2]](diffhunk://#diff-6b97099161ab32ba4fdb9ffce871d09afde260be58e0ee0b12b74c65ae392f89L246-R266)

* `src/WrapperApp/components/Simulation/SimulationCardGrid.tsx`:
  - Included `simulator` in `PaginatedSimulationsFromBackend` props and updated the function to use the passed `simulator`. [[1]](diffhunk://#diff-729d961ca25fd01f86b34b51e5294f5a529d70ff5ada7b52419e7409df13ed91R213-R218) [[2]](diffhunk://#diff-729d961ca25fd01f86b34b51e5294f5a529d70ff5ada7b52419e7409df13ed91L240-R242)

* `src/WrapperApp/components/Simulation/SimulationPanel.tsx`:
  - Passed `simulator` prop to `BackendSimulations` component.

### New Type Definitions:

* `src/types/RequestTypes.ts`:
  - Added `SimulatorNames` mapping for better simulator name management.

### CODE REVIEW

File: src/WrapperApp/components/Simulation/RunSimulationForm.tsx [hunk 1]
```diff
@@ -157,6 +157,19 @@ export function RunSimulationForm({
 			);
 	};
 
+	let simulatorMenuItems = [];
+	let defaultSimulator = forwardedSimulator;
```
Comment (grzanka) [inline src/WrapperApp/components/Simulation/RunSimulationForm.tsx:161]: Copilot suggest implementation using switch

```
let simulatorMenuItems = [];
let defaultSimulator = forwardedSimulator;

switch (forwardedSimulator) {
  case SimulatorType.SHIELDHIT:
    simulatorMenuItems.push(<MenuItem value={SimulatorType.SHIELDHIT}>SHIELD-HIT12A</MenuItem>);
    break;
  case SimulatorType.FLUKA:
    simulatorMenuItems.push(<MenuItem value={SimulatorType.FLUKA}>Fluka</MenuItem>);
    break;
  default:
    defaultSimulator = SimulatorType.SHIELDHIT;
    simulatorMenuItems = [
      <MenuItem value={SimulatorType.SHIELDHIT}>SHIELD-HIT12A</MenuItem>,
      <MenuItem value={SimulatorType.FLUKA}>Fluka</MenuItem>
    ];
    break;
}
```

image

what do you think ?

**Comment by grzanka** [comment]
Functionally it works well, but please consider code improvement.

In case single element goes into drop-down list it looks weird:
image

Maybe it could be replaced with single frozen label or something on which user cannot make any actions ?

File: src/WrapperApp/components/Simulation/BackendSimulations/BackendSimulations.tsx [hunk 2]
```diff
@@ -20,8 +21,10 @@ interface BackendSimulationsProps {
 	goToResults?: () => void;
 	setInputFiles: (inputFiles: SimulationInputFiles | undefined) => void;
 	setShowInputFilesEditor: (show: boolean) => void;
+	simulator: SimulatorType;
 }
 
+// TODO: receive simulator
```
Comment (grzanka) [inline src/WrapperApp/components/Simulation/BackendSimulations/BackendSimulations.tsx:27]: what is that TODO ?

Comment (lkwinta) [reply src/WrapperApp/components/Simulation/BackendSimulations/BackendSimulations.tsx:27]: oops, not necessary anymore

**Review by grzanka — APPROVED** [review]
